# spring config
spring:
  # hibernate config
  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
    hibernate:
      naming:
        physical-strategy: ${HIBERNATE_NAMING}

  # datasource config
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

# cloudinary
cloudinary:
  cloudName: ${CLOUDINARY_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret: ${CLOUDINARY_API_SECRET}
  secure: ${CLOUDINARY_SECURE}

# keycloak
keycloak:
  realm: ${KEYCLOAK_REALM}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  ssl-required: ${KEYCLOAK_SSL_REQUIRED}
  resource: ${KEYCLOAK_RESOURCE}
  bearer-only: ${KEYCLOAK_BEARER_ONLY}
  cors: ${KEYCLOAK_CORS}
  config:
    username: ${KEYCLOAK_USERNAME}
    password: ${KEYCLOAK_PASSWORD}
    clientId: ${KEYCLOAK_CLIENT_ID}
    clientSecret: ${KEYCLOAK_CLIENT_SECRET}