version: "1.0"

volumes:
  human_command_data:
  human_command_gradle_data:

networks:
  api_gateway_net:
    external: true
  command_database_net:
    external: true
  rabbitmq_net:
    external: true

services:
  human_command_service:
    container_name: "human-command-service"
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    ports:
      - ${HUMAN_COMMAND_HOST_PORT}:${HUMAN_COMMAND_CONTAINER_PORT}
    volumes:
      - human_command_data:${HUMAN_COMMAND_SERVICE_VOLUMES}
      - human_command_gradle_data:${HUMAN_COMMAND_GRADLE_VOLUMES}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - api_gateway_net
      - command_database_net
      - rabbitmq_net
    environment:
      HUMAN_COMMAND_HOST_PORT: ${HUMAN_COMMAND_HOST_PORT}
      HUMAN_COMMAND_CONTAINER_PORT: ${HUMAN_COMMAND_CONTAINER_PORT}
      HUMAN_COMMAND_SERVICE_VOLUMES: ${HUMAN_COMMAND_SERVICE_VOLUMES}
      HUMAN_COMMAND_GRADLE_VOLUMES: ${HUMAN_COMMAND_GRADLE_VOLUMES}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_CONTEXT_PATH: ${SERVER_CONTEXT_PATH}
      APPLICATION_NAME: ${APPLICATION_NAME}
      HIBERNATE_DIALECT: ${HIBERNATE_DIALECT}
      HIBERNATE_NAMING: ${HIBERNATE_NAMING}
      DATASOURCE_DRIVER_CLASS: ${DATASOURCE_DRIVER_CLASS}
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VIRTUAL_HOST: ${RABBITMQ_VIRTUAL_HOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_IGNORE_DECLARATION_EXCEPTION: ${RABBITMQ_IGNORE_DECLARATION_EXCEPTION}
      RABBITMQ_CONCURRENT_CONSUMERS: ${RABBITMQ_CONCURRENT_CONSUMERS}
      RABBITMQ_MAX_CONCURRENT_CONSUMERS: ${RABBITMQ_MAX_CONCURRENT_CONSUMERS}
      RABBITMQ_RECEIVE_TIMEOUT: ${RABBITMQ_RECEIVE_TIMEOUT}
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_SECURE: ${CLOUDINARY_SECURE}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_AUTH_SERVER_URL: ${KEYCLOAK_AUTH_SERVER_URL}
      KEYCLOAK_SSL_REQUIRED: ${KEYCLOAK_SSL_REQUIRED}
      KEYCLOAK_RESOURCE: ${KEYCLOAK_RESOURCE}
      KEYCLOAK_BEARER_ONLY: ${KEYCLOAK_BEARER_ONLY}
      KEYCLOAK_CORS: ${KEYCLOAK_CORS}
      KEYCLOAK_USERNAME: ${KEYCLOAK_USERNAME}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
